---   
 <img align="left" width="75" height="75"  src="../University_of_the_Punjab_logo.png"> 

<h1 align="center">Department of Data Science</h1>
<h1 align="center">Data Science Journey from Beginners to Expert</h1>

---
<h3><div align="right">Instructor: Engr. Muhammad Nadeem Majeed, Ph.D.</div></h3>     

<h1 align="center">Lecture 3.3 (NumPy-03)</h1>

# _Basic Operations on NumPy Arrays.ipynb_

<img align="center" width="500" height="500"  src="images/basicopsonnumpy.png" > 

# Learning agenda of this notebook
- Operations on numPy arrays are done element-wise. This means that you don't explicitly have to write for-loops in order to do these operations!
- A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.


<img align="left" width="450" height="400"  src="images/ufuncunary.png" > 
<img align="right" width="485" height="500"  src="images/ufuncbinary.png" > 

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

1. Scalar Math
    - On 1-D Arrays
    - On 2-D Arrays
2. Arithmetic operations
    - On 1-D Arrays
    - On 2-D Arrays
3. More Mathematical Operations
    - On 1-D Arrays
    - On 2-D Arrays
4. Aggregate Functions
    - On 1-D Arrays
    - On 2-D Arrays
5. Comparing NumPy Arrays
    - On 1-D Arrays
    - On 2-D Arrays
6. Bonus: Searching 1-D and 2-D NumPy Arrays using `numpy.where()`

In [ ]:
# To install this library in Jupyter notebook
#import sys
#!{sys.executable} -m pip install numpy

In [1]:
import numpy as np
np.__version__ , np.__path__

('1.24.3', ['C:\\Users\\Nadeem\\anaconda3\\Lib\\site-packages\\numpy'])

## 1. Scalar Math

### a. Scalar Math on 1-D Arrays

In [2]:
import numpy as np
# Create a 1-D array having 4 random integers from 1 to 9
arr = np.random.randint(1,10, size=4)
print("arr: ", arr)

# After the operation a new `ndarray` is returned
print("np.add(arr,2): ",      arr + 2)            # np.add(arr, 2))
print("np.subtract(arr,2): ", arr - 2)            # np.subtract(arr, 2))
print("np.multiply(arr,2): ", arr * 2)            # np.multiply(arr, 2))
print("np.divide(arr,2): ",   arr / 2)            # np.divide(arr, 2))
print("np.mod(arr,2): ",      arr % 2)            # np.mod(arr, 2))

arr3 = arr + 9
print(id(arr), id(arr3))

arr:  [6 9 4 9]
np.add(arr,2):  [ 8 11  6 11]
np.subtract(arr,2):  [4 7 2 7]
np.multiply(arr,2):  [12 18  8 18]
np.divide(arr,2):  [3.  4.5 2.  4.5]
np.mod(arr,2):  [0 1 0 1]
2581751596400 2581751307728


### b. Scalar Math on 2-D Arrays

In [3]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix = np.random.randint(1,10,4).reshape(2,2)
print("Original matrix:\n", matrix)

# After the operation a new `ndarray` is returned
print("np.add(matrix,2): \n",      matrix + 2)            # np.add(matrix, 2))
print("np.subtract(matrix,2): \n", matrix - 2)            # np.subtract(matrix, 2))
print("np.multiply(matrix,2): \n", matrix * 2)            # np.multiply(matrix, 2))
print("np.divide(matrix,2): \n",   matrix / 2)            # np.divide(matrix, 2))
print("np.mod(matrix,2): \n",      matrix % 2)            # np.mod(matrix, 2))

Original matrix:
 [[9 8]
 [8 7]]
np.add(matrix,2): 
 [[11 10]
 [10  9]]
np.subtract(matrix,2): 
 [[7 6]
 [6 5]]
np.multiply(matrix,2): 
 [[18 16]
 [16 14]]
np.divide(matrix,2): 
 [[4.5 4. ]
 [4.  3.5]]
np.mod(matrix,2): 
 [[1 0]
 [0 1]]


## 2. Arithmetic Operations

### a. Arithmetic Operations on 1-D Arrays

In [6]:
import numpy as np
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,10, size=4)
arr2 = np.random.randint(1,10, size=4)
print("arr1: ", arr1)
print("arr2: ", arr2)

# After the operation a new `ndarray` is returned
print("np.add(arr1, arr2) = ",      arr1 + arr2)     # np.add(arr1, arr2)
print("np.subtract(arr1, arr2) = ", arr1 - arr2)     # np.subtract(arr1, arr2)
print("np.multiply(arr1, arr2) = ", arr1 * arr2)     # np.multiply(arr1, arr2)
print("np.divide(arr1, arr2) = ",   arr1  / arr2)    # np.divide(arr1, arr2)
print("np.mod(arr1, arr2) = ",      arr1  % arr2)    # np.mod(arr1, arr2) # np.remainder(arr1, arr2)

arr1:  [7 8 6 7]
arr2:  [4 1 9 3]
np.add(arr1, arr2) =  [11  9 15 10]
np.subtract(arr1, arr2) =  [ 3  7 -3  4]
np.multiply(arr1, arr2) =  [28  8 54 21]
np.divide(arr1, arr2) =  [1.75       8.         0.66666667 2.33333333]
np.mod(arr1, arr2) =  [3 0 6 1]


### b. Arithmetic Operations on 2-D Arrays

In [4]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix1 = np.random.randint(1,10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))
print("matrix1: \n", matrix1)
print("matrix2: \n", matrix2)

# After the operation a new `ndarray` is returned
print("np.add(matrix1 , matrix2) = \n",      matrix1 + matrix2) # np.add(matrix1 , matrix2)
print("np.subtract(matrix1 , matrix2) = \n", matrix1 - matrix2) # np.subtract(matrix1 , matrix2)
print("np.multiply(matrix1 , matrix2) = \n", matrix1 * matrix2) # np.multiply(matrix1 , matrix2)
print("np.divide(matrix1 , matrix2) = \n",   matrix1 / matrix2) # np.divide(matrix1 , matrix2)
print("np.mod(matrix1 , matrix2) = \n",      matrix1 % matrix2) # np.remainder(matrix1 , matrix2)

matrix1: 
 [[1 5]
 [8 9]]
matrix2: 
 [[4 4]
 [4 8]]
np.add(matrix1 , matrix2) = 
 [[ 5  9]
 [12 17]]
np.subtract(matrix1 , matrix2) = 
 [[-3  1]
 [ 4  1]]
np.multiply(matrix1 , matrix2) = 
 [[ 4 20]
 [32 72]]
np.divide(matrix1 , matrix2) = 
 [[0.25  1.25 ]
 [2.    1.125]]
np.mod(matrix1 , matrix2) = 
 [[1 1]
 [0 1]]


## 3. More Mathematical Operations

### a. Mathematical Operations on 1-D Array

In [11]:
# Creating 1-D array of 5 elements of random floats between 1 and 10
arr = np.random.rand(5)*10
print("Original ndarray: ", arr)


# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.abs(arr) = ", np.abs(arr))
print("np.square(arr) = ", np.square(arr))
print("np.sqrt(arr) = ", np.sqrt(arr))
print("np.cbrt(arr) = ", np.cbrt(arr))
print("np.log(arr) = ", np.log(arr))
print("np.log2(arr) = ", np.log2(arr))
print("np.log10(arr) = ", np.log10(arr))
print("np.isnan(arr) = ", np.isnan(arr))
print("np.ceil(arr) = ", np.ceil(arr))
print("np.floor(arr) = ", np.floor(arr))
print("np.cumsum(arr) = ", np.cumsum(arr))

Original ndarray:  [0.99739248 8.02527762 4.37817679 5.62638568 9.26560222]
np.abs(arr) =  [0.99739248 8.02527762 4.37817679 5.62638568 9.26560222]
np.square(arr) =  [ 0.99479175 64.40508086 19.16843197 31.65621586 85.85138455]
np.sqrt(arr) =  [0.99869539 2.83289209 2.09240933 2.37200035 3.04394517]
np.cbrt(arr) =  [0.99913007 2.00210425 1.63592893 1.77859268 2.10034781]
np.log(arr) =  [-0.00261093  2.08259626  1.47663238  1.72746726  2.22630886]
np.log2(arr) =  [-0.00376677  3.0045513   2.13033021  2.49220845  3.21188475]
np.log10(arr) =  [-0.00113391  0.90446006  0.64129329  0.7502295   0.96687365]
np.isnan(arr) =  [False False False False False]
np.ceil(arr) =  [ 1.  9.  5.  6. 10.]
np.floor(arr) =  [0. 8. 4. 5. 9.]
np.cumsum(arr) =  [ 0.99739248  9.0226701  13.40084688 19.02723256 28.29283479]


### b. Mathematical Operations on 2-D Array

In [13]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix = np.random.randint(1,10, size=(2, 2))
print("matrix: \n", matrix)

# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.square(matrix) = \n", np.square(matrix))
print("np.sqrt(matrix) = \n", np.sqrt(matrix))
print("np.log2(matrix) = \n", np.log2(matrix))
print("np.isnan(matrix) = \n", np.isnan(matrix))
print("np.ceil(matrix) = \n", np.ceil(matrix))
print("np.floor(matrix) = \n", np.floor(matrix))
print("np.cumsum(matrix) = \n", np.cumsum(matrix))
np.cumsum(matrix,axis=0) # column sum
np.cumsum(matrix,axis=1)


matrix: 
 [[7 6]
 [4 6]]
np.square(matrix) = 
 [[49 36]
 [16 36]]
np.sqrt(matrix) = 
 [[2.64575131 2.44948974]
 [2.         2.44948974]]
np.log2(matrix) = 
 [[2.80735492 2.5849625 ]
 [2.         2.5849625 ]]
np.isnan(matrix) = 
 [[False False]
 [False False]]
np.ceil(matrix) = 
 [[7 6]
 [4 6]]
np.floor(matrix) = 
 [[7 6]
 [4 6]]
np.cumsum(matrix) = 
 [ 7 13 17 23]


array([[ 7, 13],
       [ 4, 10]])

## 4. Aggregate Functions

### a. Aggregate Functions on 1-D Arrays

In [5]:
# Create a 1-D array having 5 random integers from 1 to 9
arr = np.random.randint(1, 10, size=5)
print("arr: ", arr)

# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.min(arr) = ",     np.min(arr))
print("np.max(arr) = ",     np.max(arr))
print("np.sum(arr) = ",     np.sum(arr))
print("np.prod(arr) = ", np.prod(arr))

arr:  [6 7 1 2 6]
np.min(arr) =  1
np.max(arr) =  7
np.sum(arr) =  22
np.prod(arr) =  504


In [17]:
# Create a 1-D array having 5 random integers from 1 to 9
arr = np.random.randint(1, 10, size=5)
print("arr: ", arr)

#Arithmetic mean is the sum of elements along an axis divided by the number of elements. 
print("np.mean(arr) = ",    np.mean(arr))

# The np.average() function computes the weighted average, by multiplying of each array element by its weight
# The np.average() is same as np.mean(), when weight is not specified
print("np.average(arr) = ", np.average(arr))

# Considering an array [1,2,3,4] and corresponding weights [4,3,2,1], the weighted average is calculated by 
# adding the product of the corresponding elements and dividing the sum by the sum of weights.
#             Weighted average = (1*4+2*3+3*2+4*1)/(4+3+2+1)

arr1 = np.array([10,20,30])
wts = np.array([1,2,3])
print("\narr1: ", arr1)
print("wts:  ", wts)
print("np.average(arr1, weights=wts) = ", np.average(arr1, weights= wts))

# [(10∗1)+(20∗2)+(30∗3)]/(1+2+3)​≈23.33


arr:  [3 2 7 2 6]
np.mean(arr) =  4.0
np.average(arr) =  4.0

arr1:  [10 20 30]
wts:   [1 2 3]
np.average(arr1, weights=wts) =  23.333333333333332


In [25]:
# Create a 1-D array having 10 random integers from 1 to 99
arr = np.random.randint(1, 100, size=10)
print("arr: ", arr)

# Median is the value separating the higher half of a data sample from the lower half.
print("np.median(arr) = ",  np.median(arr))

# Percentile is the value below which a given percentage of observations in a group of observations fall.
# 50th percentile is the score at or below which 50% of the scores in the distribution may be found.
print("np.percentile(arr,50) = ",     np.percentile(arr,50))
print("np.percentile(arr,0) = ",     np.percentile(arr,0))
print("np.percentile(arr,100) = ",     np.percentile(arr,100))

# The variance measures the average degree to which each point differs from the mean
# Variance is calculated as the average of squared deviations from mean, i.e., mean((x - x.mean())**2).
print("np.var(arr) = ",    np.var(arr))


# Standard deviation checks how spread out a group of numbers is from the mean
# It is the square root of variance: sqrt(mean((x - x.mean())**2))
print("np.std(arr) = ",    np.std(arr))


arr:  [87  7 96 25 37 65 59 75  4  6]
np.median(arr) =  48.0
np.percentile(arr,50) =  48.0
np.percentile(arr,0) =  4.0
np.percentile(arr,100) =  96.0
np.var(arr) =  1095.8899999999999
np.std(arr) =  33.10422933704997


### b. Aggregate Functions on 2-D Arrays

In [35]:
import numpy as np
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10,9).reshape(3,3)
print("matrix: \n", matrix)

print("np.sum(matrix, axis=0) = ",     np.sum(matrix, axis=0))
print("np.sum(matrix, axis=1) = ",     np.sum(matrix, axis=1))


matrix: 
 [[3 5 9]
 [7 3 4]
 [8 3 6]]
np.sum(matrix, axis=0) =  [18 11 19]
np.sum(matrix, axis=1) =  [17 14 17]


In [36]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)

print("np.min(matrix, axis=0) = ",     np.min(matrix, axis=0))
print("np.min(matrix, axis=1) = ",     np.min(matrix, axis=1))

matrix: 
 [[7 4 8]
 [1 6 3]
 [9 3 1]]
np.min(matrix, axis=0) =  [1 3 1]
np.min(matrix, axis=1) =  [4 1 1]


In [38]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)


print("np.mean(matrix, axis=0) = ",     np.mean(matrix, axis=0))
print("np.mean(matrix, axis=1) = ",     np.mean(matrix, axis=1))

matrix: 
 [[3 4 8]
 [1 8 6]
 [4 2 8]]
np.mean(matrix, axis=0) =  [2.66666667 4.66666667 7.33333333]
np.mean(matrix, axis=1) =  [5.         5.         4.66666667]


In [ ]:
# Create a 3x3 (2-D array) initialized with random integers from 1 to 9
matrix = np.random.randint(1,10, size=(3, 3))
print("matrix: \n", matrix)

# Median is the value separating the
#  higher half of a data sample from the lower half.
print("np.median(matrix, axis=0) = ",     np.median(matrix, axis=0))
print("np.median(matrix, axis=1) = ",     np.median(matrix, axis=1))

matrix: 
 [[9 1 4]
 [8 5 4]
 [6 4 5]]
np.median(matrix, axis=0) =  [8. 4. 4.]
np.median(matrix, axis=1) =  [4. 5. 5.]


Please do practice calculating the percentile, variance and standard deviation along different axis of a 2-D array

## 5. Comparing NumPy Arrays

### a. Comparing NumPy 1-D Arrays
- Returns a Boolean numpy array containing True/False after doing element wise comparison

In [41]:
import numpy as np
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,10, size=4)
arr2 = np.random.randint(1,10, size=4)
print("arr1: ", arr1)
print("arr2: ", arr2)
print("np.equal(arr1, arr2) = ",      arr1 == arr2)      # np.equal(arr1, arr2)
print("np.not_equal(arr1, arr2) = ",  arr1 != arr2)      # np.not_equal(arr1, arr2)

print("np.greater(arr1, arr2) = ",      arr1 > arr2)     # np.greater(arr1, arr2)
print("np.greater_equal(arr1, arr2) = ",  arr1 >= arr2)  # np.greater_equal(arr1, arr2)


print("np.less(arr1, arr2) = ",      arr1 < arr2)        # np.less(arr1, arr2)
print("np.less_equal(arr1, arr2) = ",  arr1 <= arr2)     # np.less_equal(arr1, arr2)

arr1:  [2 3 1 7]
arr2:  [6 3 8 5]
np.equal(arr1, arr2) =  [False  True False False]
np.not_equal(arr1, arr2) =  [ True False  True  True]
np.greater(arr1, arr2) =  [False False False  True]
np.greater_equal(arr1, arr2) =  [False  True False  True]
np.less(arr1, arr2) =  [ True False  True False]
np.less_equal(arr1, arr2) =  [ True  True  True False]


### b. Comparing NumPy 2-D Arrays

In [42]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix1 = np.random.randint(1,10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))
print("matrix1: \n", matrix1)
print("matrix2: \n", matrix2)



print("np.equal(matrix1, matrix2) = \n",        matrix1 == matrix2)     
print("np.not_equal(matrix1, matrix2) = \n",    matrix1 != matrix2)     

print("np.greater(matrix1, matrix2) = \n",      matrix1 > matrix2)    
print("np.greater_equal(matrix1, matrix2) = \n",matrix1 >= matrix2) 

print("np.less(matrix1, matrix2) = \n",         matrix1 < matrix2)       
print("np.less_equal(matrix1, matrix2) = \n",   matrix1 <= matrix2)     

matrix1: 
 [[6 1]
 [5 4]]
matrix2: 
 [[2 9]
 [2 7]]
np.equal(matrix1, matrix2) = 
 [[False False]
 [False False]]
np.not_equal(matrix1, matrix2) = 
 [[ True  True]
 [ True  True]]
np.greater(matrix1, matrix2) = 
 [[ True False]
 [ True False]]
np.greater_equal(matrix1, matrix2) = 
 [[ True False]
 [ True False]]
np.less(matrix1, matrix2) = 
 [[False  True]
 [False  True]]
np.less_equal(matrix1, matrix2) = 
 [[False  True]
 [False  True]]


## 6. Searching NumPy Arrays using `numpy.where()`

### a. Searching NumPy 1-D Arrays

- The `numpy.where()` method is used to search NumPy arrays for the index values of any element which matches the condition passed as a parameter to the function.
```
numpy.where(condition, [x, y])
```
    - condition : When True, yield x, otherwise yield y. If x and y are not given just return the value of the array
    - Returns: ndarray or tuple of ndarrays. If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4, 9, 2, 3, 8])
t1 = np.where(arr == 4)
print(t1)


(array([3, 5, 6]),)


In [51]:
a1=np.random.randint(1,10,20)
print(a1)
np.where(a1==4)


[5 6 6 1 5 1 4 4 3 8 6 3 1 7 2 9 7 9 3 9]


(array([6, 7]),)

Note: The result is a tuple of 1-D arrays having a single tuple containing the index

In [ ]:
import numpy as np
arr = np.array([1, 0, 3, 9, 5, 2, 0, 8])
t1 = np.where(arr == 0)
print(t1)


(array([1, 6], dtype=int64),)


In [55]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
t1 = np.where(arr%2 == 0)
print(t1)

(array([1, 3, 5, 7]),)


In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
t1 = np.where(arr%2 == 0, "Even", "Odd")
print(t1)

['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


In [10]:
# nmb divisible by 7
arr=np.random.randint(1,20,10)
print(arr)
np.where(arr%7==0,'Divisible','Not Divisible')


[14  4  3 14 16  2 19 17 10  7]


array(['Divisible', 'Not Divisible', 'Not Divisible', 'Divisible',
       'Not Divisible', 'Not Divisible', 'Not Divisible', 'Not Divisible',
       'Not Divisible', 'Divisible'], dtype='<U13')

Note: The result is a simple 1-D array, when you use the x and y arguments to `np.where()`

### b. Searching NumPy 2-D Arrays

- The `numpy.where()` method is used to search NumPy arrays for the index values of any element which matches the condition passed as a parameter to the function.
```
numpy.where(condition, [x, y])
```
    - condition : When True, yield x, otherwise yield y. If x and y are not given just return the value of the array
    - Returns: ndarray or tuple of ndarrays. If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

In [13]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 4], [4, 9, 2], [3, 8, 6]])
print("matrix: \n", matrix)
t1 = np.where(matrix == 4)
print(t1)

matrix: 
 [[1 2 3]
 [4 5 4]
 [4 9 2]
 [3 8 6]]
(array([1, 1, 2]), array([0, 2, 0]))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for three elements at indices `(1,0)`, `(1,2)` and `(2,0)`

In [14]:
import numpy as np
matrix = np.array([[1, 2, 0], [4, 5, 0], [4, 9, 2], [3, 0, 6]])
print("matrix: \n", matrix)
t1 = np.where(matrix == 0)
print(t1)


matrix: 
 [[1 2 0]
 [4 5 0]
 [4 9 2]
 [3 0 6]]
(array([0, 1, 3]), array([2, 2, 1]))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for three elements at indices:
`(0,2)`, `(1,2)` and `(3,1)`

In [15]:
import numpy as np
matrix = np.array([[1, 2, 3], [5, 7, 3], [4, 9, 1], [3, 5, 3]])
print("matrix: \n", matrix)
t1 = np.where(matrix%2 == 0)
print(t1)

matrix: 
 [[1 2 3]
 [5 7 3]
 [4 9 1]
 [3 5 3]]
(array([0, 2]), array([1, 0]))


**Note:** The result is a tuple of 1-D arrays having two tuples. The condition is true for two elements at indices:
`(0,2)` and `(1,0)`

In [18]:
import numpy as np
matrix = np.array([[1, 2, 3], [5, 7, 3], [4, 9, 1], [3, 5, 3]])
print("matrix: \n", matrix)
t1 = np.where(matrix%2 == 0, True, False)
print(t1)

matrix: 
 [[1 2 3]
 [5 7 3]
 [4 9 1]
 [3 5 3]]
[[False  True False]
 [False False False]
 [ True False False]
 [False False False]]


**Note:** The result is a simple 2-D array, when you use the `x` and `y` arguments to `np.where()`

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [4, 5, 4, 2], [8, 4, 9, 2], [4, 3, 8, 6]])
t1 = np.where(arr == 4)
print(t1)

(array([0, 1, 1, 2, 3]), array([3, 0, 2, 1, 0]))
