In [8]:
# Numpy vs List 
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time
start=time.time()
for i in range (len(a)):
    c.append(a[i]+b[i])

print(time.time()-start)
    
    

6.653068780899048


In [10]:
#Numpy 
import numpy as np

a=np.arange(10000000)
b=np.arange(10000000,20000000)
import time
start = time.time()
c=a+b

print(time.time()-start)



0.05952763557434082


In [11]:
a=[i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [13]:
a=np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000112

In [ ]:
# Advance Indexing
# Fancy Indexing
# extract 1 2 and 4th row
#extract the 2nd and 4th column
a=np.arange(24).reshape(6,4)
print(a)
print(a[[0,2,3]])
print(a[:,[1,3]])



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]
 [21 23]]


In [30]:
# Boolean indexing 
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[63, 63,  6, 21],
       [94, 84,  7, 77],
       [81, 87, 28, 52],
       [26, 73, 58,  2],
       [46, 11, 52, 56],
       [30, 96, 92, 24]], dtype=int32)

In [32]:
# find Elements greater than 50
a[a>50]


array([63, 63, 94, 84, 77, 81, 87, 52, 73, 58, 52, 56, 96, 92],
      dtype=int32)

In [33]:
# find the even nmb
a[a%2==0]

array([ 6, 94, 84, 28, 52, 26, 58,  2, 46, 52, 56, 30, 96, 92, 24],
      dtype=int32)

In [38]:
#find Elements greater than 50+find the even nmb
a[(a>50)&(a%2==0)]

array([94, 84, 52, 58, 52, 56, 96, 92], dtype=int32)

In [42]:
# Find all the numbers not divisible by the 7
a[~(a%7==0)]

array([ 6, 94, 81, 87, 52, 26, 73, 58,  2, 46, 11, 52, 30, 96, 92, 24],
      dtype=int32)

In [45]:
# Broad casting : The term broadcasting describes how NumPy treats arrays with different shapes
# during arithmetic operations.
#The smaller array is "broadcast- across the larger array so that they have compatible shapes.
a=np.arange(6).reshape(2,3)
b=np.arange(3,6).reshape(1,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[3 4 5]]
[[ 3  5  7]
 [ 6  8 10]]


In [46]:
a=np.arange(12).reshape(4,3)
b=np.arange(6,9).reshape(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[6 7 8]
[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]


In [47]:
a=np.arange(12).reshape(3,4)
b=np.arange(6,9).reshape(3)
print(a)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[6 7 8]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a=np.arange(3).reshape(1,3)
b=np.arange(6,9).reshape(3,1)
print(a)
print(b)
print(a+b)

[[0 1 2]]
[[6]
 [7]
 [8]]
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [51]:
a=np.arange(3).reshape(3,1)
b=np.arange(6,9).reshape(3)
print(a)
print(b)
print(a+b)

[[0]
 [1]
 [2]]
[6 7 8]
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [54]:
# WOrking with the mathematical formulas 
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# Sigmoid  formula 
def Sigmoid(a):
    return 1/(1+np.exp(-(a)))
a=np.arange(10)
Sigmoid(a)


array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [ ]:
# mean squared  error
actual=np.random.randint(1,50,25)
predicted=np.random.randint(1,50,25)
print(actual)
print(predicted)
def MSE(actual,predicted):
    return np.mean((actual-predicted)**2)

MSE(actual,predicted)
    

[11 27 16 33 21  3  8 46 16  2 44 24 18 21 13 25 29 43 46 29 21  6 35 21
 22]
[33  2 37 38 36 18 14  7 27 43 39 37  1 25 20 33 22 25 30  3 18  9  5 17
 25]


np.float64(329.76)

In [ ]:
# Binary Cross Entropy 
# task make the formula of this 


In [ ]:
# Dealing with the missing values
a=np.array([1,2,3,np.nan,np.nan,6])
print(a)
a[~np.isnan(a)]

[ 1.  2.  3. nan nan  6.]


array([1., 2., 3., 6.])

In [3]:
# Plotting Graphs
import matplotlib.pyplot as plt
x=np.linspace(-10,10,100)
y=x 
plt.plot(x,y)


ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
x=np.linspace(-10,10,100)
y=x**2
plt.plot(x,y)

In [72]:
x=np.linspace(-10,10,100)
y=np.sin(x)
plt.plot(x,y)

NameError: name 'plt' is not defined

In [2]:
# Sigmoid 
x=np.linspace(-10,10,100)
y=(1/(1+np.exp(-x)))
plt.plot(x,y)


NameError: name 'np' is not defined