In [3]:
import numpy as np 
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a2


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [5]:
# Function on the numpy array 
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[25.,  6., 48.],
       [ 6., 88., 29.],
       [14., 93., 13.]])

In [ ]:
# max element in each columb 
np.max(a1,axis=0)


array([48., 88., 93.])

In [8]:
# max element in each row 
np.max(a1,axis=1)

array([48., 88., 93.])

In [12]:
#mean / median / std / var
np.mean(a1)
np.median(a1,axis=0)
np.var(a1)
np.std(a1)


np.float64(31.762233960677882)

In [14]:
#dot product
a1=np.arange(12).reshape((3,4))
a2=np.arange(12,24).reshape((4,3))
a3=np.dot(a1,a2)
a3

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [16]:
# log and exponents 
np.exp(a1)
np.log(a1)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17596\3477358494.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [ ]:
#round / floor  / ceil
np.round(np.random.random((3,4))*100)


array([[60., 10.,  5., 45.],
       [14., 54., 60., 87.],
       [40., 21., 72., 42.]])

In [22]:
#indexing and slicing 
a1=np.arange(1,10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
a1[-1]

np.int64(9)

In [24]:
a2[1,3]

np.int64(7)

In [28]:
a3[1,0,1]
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
#slicing
a1[2:7] # 3,4,4,5,6

 

array([3, 4, 5, 6, 7])

In [42]:
a2[:,2] # col 3


array([ 2,  6, 10])

In [44]:
a2[1,:]

array([4, 5, 6, 7])

In [46]:
#extract 4 5 8 9
# how ?
a2[1:,0:2]

array([[4, 5],
       [8, 9]])

In [47]:
# extract 0,3,8,9
a2[0::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
# extract the 1,3,9,11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [50]:
# extract 4,7
a2[1,::3]

array([4, 7])

In [ ]:
#extract 1 2 3
#        5,6,7
a2[0:2,1::] 

array([[1, 2, 3],
       [5, 6, 7]])

In [70]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [80]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#print the 2nd row of the 1st 2d array
a3[0,1]

array([3, 4, 5])

In [79]:
#Print the mid column of the 2nd 2d array
a3[1,::,1]

array([10, 13, 16])

In [88]:
a3[2,1::,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
#print 0,2,18,20
a3[0::2,0::3,::2]

array([[ 0,  2],
       [18, 20]])

In [95]:
#Loops on the arrays 
for i in a1:
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 

In [101]:
for i in a3:
    print(i)
    print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]

[[18 19 20]
 [21 22 23]
 [24 25 26]]



In [104]:
for i in np.nditer(a3):
    print(i,end=" ")
     

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [ ]:
# Reshaping
# transpose
#ravel
a2.T  # transpose 



array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [107]:
# ravel
a3.ravel()   # convert the given dimention array to the 1D array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

stacking

In [113]:
# horizontal Stacking 
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))
#np.hstack((a4,a5,a4,a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [115]:
# Vertical Stacking 
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [124]:
#horizontal Splitting 
np.hsplit(a4,2)


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [127]:
# vertical splitting 
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]