In [3]:
import numpy as np
a=np.random.randint(1,100,15)
print(a)
np.sort(a)

[91 68 45 82 32 51 80 65 39 64  3  8 51 12 97]


array([ 3,  8, 12, 32, 39, 45, 51, 51, 64, 65, 68, 80, 82, 91, 97],
      dtype=int32)

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
print(b)
np.sort(b)
# it'll sort row wise


[[62  5 11  5]
 [60 50 93 59]
 [51 82 32 38]
 [71 14 85 93]
 [30  2  5 61]
 [57 36 44 51]]


array([[ 5,  5, 11, 62],
       [50, 59, 60, 93],
       [32, 38, 51, 82],
       [14, 71, 85, 93],
       [ 2,  5, 30, 61],
       [36, 44, 51, 57]], dtype=int32)

In [8]:
np.sort(b,axis=0) 
# Column wise sorting

array([[20, 11, 19, 31],
       [23, 14, 62, 34],
       [24, 41, 76, 70],
       [54, 46, 85, 72],
       [58, 48, 88, 74],
       [78, 65, 98, 98]], dtype=int32)

In [9]:
np.sort(b,axis=1) 
# Row wise wise sorting

array([[24, 46, 74, 85],
       [48, 72, 78, 98],
       [14, 23, 34, 62],
       [11, 31, 54, 88],
       [58, 65, 70, 76],
       [19, 20, 41, 98]], dtype=int32)

In [15]:
# reverse order Sorting Row wise
np.sort(b,axis=1)[:,::-1]

array([[85, 74, 46, 24],
       [98, 78, 72, 48],
       [62, 34, 23, 14],
       [88, 54, 31, 11],
       [76, 70, 65, 58],
       [98, 41, 20, 19]], dtype=int32)

In [17]:
# Sort the column Column wise Reverse ordr
np.sort(b,axis=0)[::-1,:]

array([[78, 65, 98, 98],
       [58, 48, 88, 74],
       [54, 46, 85, 72],
       [24, 41, 76, 70],
       [23, 14, 62, 34],
       [20, 11, 19, 31]], dtype=int32)

In [18]:
np.append(a,18)

array([31, 44, 39, 51, 45, 66, 91, 71, 32,  3,  2, 41,  4, 98,  2, 18])

In [5]:
# append the new row in the 2D array
new_row=np.random.randint(1,100,4).reshape(1,4)
new_row
np.append(b,new_row,axis=0)



array([[62,  5, 11,  5],
       [60, 50, 93, 59],
       [51, 82, 32, 38],
       [71, 14, 85, 93],
       [30,  2,  5, 61],
       [57, 36, 44, 51],
       [11, 60, 54, 49]], dtype=int32)

In [ ]:
# new column added

new_col=np.random.randint(1,100,6).reshape(6,1)
new_col
print(b)
np.append(b,new_col,axis=1)

[[24 46 85 74]
 [78 48 98 72]
 [23 14 62 34]
 [54 11 88 31]
 [58 65 76 70]
 [20 41 19 98]]


array([[24, 46, 85, 74, 34],
       [78, 48, 98, 72, 40],
       [23, 14, 62, 34,  3],
       [54, 11, 88, 31, 60],
       [58, 65, 76, 70, 91],
       [20, 41, 19, 98, 59]], dtype=int32)

In [ ]:
# Contatination on the Np Array 
c=np.arange(1,100,6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[86 97 71]
 [99 44  4]]
[[ 6  7  8]
 [ 9 10 11]]


In [51]:
row_cont=np.concatenate((c,d),axis=0)
col_cont=np.concatenate((c,d),axis=1)
print(row_cont)
print(col_cont)

[[86 97 71]
 [99 44  4]
 [ 6  7  8]
 [ 9 10 11]]
[[86 97 71  6  7  8]
 [99 44  4  9 10 11]]


In [6]:
# Unique values in the array
arr=np.array([1,1,1,13,3,4,2,4,5,6,4,3,22,1]
             )
np.unique(arr)


array([ 1,  2,  3,  4,  5,  6, 13, 22])

In [71]:
# Expand Dimentions of the array 
# example convert the 1D array to 2D array
# it  is the Way to make the row vector and column vector
print("The orignal shape of the array is ",arr.shape)
x=np.expand_dims(arr,axis=1)
print(x)
print(" Shape of the x is ",x.shape)
y=np.expand_dims(arr,axis=0)
print(y)
print("The shape of the y is ",y.shape)
 

The orignal shape of the array is  (14,)
[[ 1]
 [ 1]
 [ 1]
 [13]
 [ 3]
 [ 4]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 4]
 [ 3]
 [22]
 [ 1]]
 Shape of the x is  (14, 1)
[[ 1  1  1 13  3  4  2  4  5  6  4  3 22  1]]
The shape of the y is  (1, 14)


In [7]:
# it gives the index of the elements 
# Grateer than 50
import numpy as np
a=np.random.randint(1,100,20)
print(a)
np.where(a>50)

[56 15 46 62 75 50 13  6  3 65 74 86 75 60 94 54 79 44  5 67]


(array([ 0,  3,  4,  9, 10, 11, 12, 13, 14, 15, 16, 19]),)

In [13]:
# np.where(condition,true,false)
# jo 50 se greater han wo same rehne gy baki 0 kr den gy

np.where(a>50,0,a)

array([ 0, 47,  0,  0, 14,  0, 39,  0, 23,  0,  0,  0, 29,  0, 12,  0, 11,
       43,  0,  0], dtype=int32)

In [19]:

# Even nmb ko skip krna ha 
np.where(a%2==0,0
         ,a)

array([ 0, 47, 59,  0,  0, 87, 39,  0, 23,  0,  0,  0, 29, 63,  0,  0, 11,
       43, 83,  0], dtype=int32)

In [8]:
# return the Maximum element index
np.argmax(a)

np.int64(14)

In [9]:
# row wise MAx element index 
b=np.random.randint(1,100,20).reshape(5,4)

print(b)
np.argmax(b,axis=1)

[[88 97 62 85]
 [34 18 19 43]
 [60 33 78 24]
 [12 64  9 66]
 [40 37 22 39]]


array([1, 3, 2, 3, 0])

In [28]:
# Column wise MAx element index 
b=np.random.randint(1,100,20).reshape(5,4)
print(b)
np.argmax(b,axis=0)

[[97 28 19 28]
 [54  3 59 25]
 [87 31 77  8]
 [93 33 59  2]
 [39 33 61 18]]


array([0, 3, 2, 0])

In [30]:
# argmin 
#min element
np.argmin(a)

np.int64(16)

In [34]:
# Cululator Sum (The sum like the fabinacci series ith
# #element is the sum of all the previous elements
print(a)
np.cumsum(a)

[74 47 59 96 14 87 39 60 23 56 76 70 29 63 12 54 11 43 83 66]


array([  74,  121,  180,  276,  290,  377,  416,  476,  499,  555,  631,
        701,  730,  793,  805,  859,  870,  913,  996, 1062])

In [ ]:
# Column wise CumSum
print(b)
np.cumsum(b,axis=0)


[[97 28 19 28]
 [54  3 59 25]
 [87 31 77  8]
 [93 33 59  2]
 [39 33 61 18]]


array([[ 97,  28,  19,  28],
       [151,  31,  78,  53],
       [238,  62, 155,  61],
       [331,  95, 214,  63],
       [370, 128, 275,  81]])

In [39]:
# ROw wise CumSum
print(b)
np.cumsum(b,axis=1)


[[97 28 19 28]
 [54  3 59 25]
 [87 31 77  8]
 [93 33 59  2]
 [39 33 61 18]]


array([[ 97, 125, 144, 172],
       [ 54,  57, 116, 141],
       [ 87, 118, 195, 203],
       [ 93, 126, 185, 187],
       [ 39,  72, 133, 151]])

In [42]:
# give the Product of comulator elements
z=np.random.randint(1,10,10)
np.cumprod(z)

array([       7,       56,      336,      672,     6048,    24192,
         169344,   846720,  6773760, 20321280])

In [ ]:
# percentile (n/N)*100
#file nmb theory 

np.percentile(a,100)

np.float64(96.0)

In [49]:
# Histogram
# 10 se 20 ke drmyn ktny values han uski frequency btata ha 
# 20 se 30 ke drmyn ktny ha uski btata ha 
# and so on
print(a)
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])


[74 47 59 96 14 87 39 60 23 56 76 70 29 63 12 54 11 43 83 66]


(array([0, 3, 2, 1, 2, 3, 3, 3, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [56]:
item=[74,20,39,40,50,60,70]
np.isin(a,item)


array([ True, False, False, False, False, False,  True,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False])

In [ ]:
#makes the Image of the array
# print(a)
np.flip(a)

[74 47 59 96 14 87 39 60 23 56 76 70 29 63 12 54 11 43 83 66]


array([66, 83, 43, 11, 54, 12, 63, 29, 70, 76, 56, 23, 60, 39, 87, 14, 96,
       59, 47, 74], dtype=int32)

In [59]:
print(b)
np.flip(b)

[[97 28 19 28]
 [54  3 59 25]
 [87 31 77  8]
 [93 33 59  2]
 [39 33 61 18]]


array([[18, 61, 33, 39],
       [ 2, 59, 33, 93],
       [ 8, 77, 31, 87],
       [25, 59,  3, 54],
       [28, 19, 28, 97]], dtype=int32)

In [72]:
# this make the permanent changes

np.put(a,[0,1,2],[10,20,30])

print(a)

[10 20 30 96 14 87 39 60 23 56 76 70 29 63 12 54 11 43 83 66]


In [78]:
# give the index
# can also b use to multiple items
print(a)
np.delete(a,[0,2,3,4])


[10 20 30 96 14 87 39 60 23 56 76 70 29 63 12 54 11 43 83 66]


array([20, 87, 39, 60, 23, 56, 76, 70, 29, 63, 12, 54, 11, 43, 83, 66],
      dtype=int32)

In [8]:
# Sets Functiom
x1=np.arange(1,20,2)
x2=np.arange(10,20)
print(x1)
print(x2)
np.union1d(x1,x2)
np.intersect1d(x1,x2)
np.setdiff1d(x1,x2)
np.setxor1d(x1,x2)
np.isin(x1,15)
x1[np.isin(x1,15)]

[ 1  3  5  7  9 11 13 15 17 19]
[10 11 12 13 14 15 16 17 18 19]


array([15])

In [9]:
# flips the values between the min to max
np.clip(x1,a_min=10,a_max=20)


array([10, 10, 10, 10, 10, 11, 13, 15, 17, 19])

In [15]:
a1=np.linspace(1,15,6) # linspace gives the equi distant elements
a1

array([ 1. ,  3.8,  6.6,  9.4, 12.2, 15. ])