In [1]:
# stride in the python 
# the strides attribute of an array (arr.strides) returns a tuple of
# integers representing the byte offsets (strides) 
# needed to step from one element to the next along each dimension of the array.
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3), dtype: int64 (8 bytes/item)
print(arr.strides)  # Output: (24, 8)

# 24 (row stride): To go to the next row, skip 3 elements × 8 bytes = 24 bytes.
# 8 (col stride): To go to the next column in the same row, skip 1 element × 8 bytes = 8 bytes.

(24, 8)


In [ ]:
np.zeros((2,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [15]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [21]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place higher
eye_arr = np.eye(4, 4, k = 1, dtype=int)
eye_arr

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [22]:
# creating 2-D array of int type using eye function with 4 rows and 3 columns having 1's at one place lower
eye_arr = np.eye(4, 3,-1, dtype=int)
eye_arr

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
# FormString 
np.fromstring('2 3 4 5 6',dtype=np.int8,sep=" ")
#np.fromstring('2 3 4 5 6',sep=" ")

array([2, 3, 4, 5, 6], dtype=int8)